### ISSUE TITLE
Animation Scroll for mobile sometimes does not let you scroll down

### ISSUE THREAD

**Issue by IvailoStoyanov** [biotope/website#116]
This issue appears after resizing to mobile (sometimes)

**Comment by jurekbarth** [comment]
I would add that thing is buggy on all browsers. I have issues in latest Chrome while scrolling. The scrollbar jumps like crazy, can we use scroll snap points instead of some javascript interception? It has [quite good support](https://caniuse.com/#feat=css-snappoints) and there's imho no reasoning that the UX is worse if they can just scroll through it.
