### ISSUE TITLE
Test cookiebar accept and decline functionalities when gtm is published

### ISSUE THREAD

**Issue by clemensf** [biotope/website#145]
## Expected behavior
clicking accept sets required google and linkedin cookies 
clicking decline deletes all cookies previously set.

## Actual behavior
currently not yet testable wit gtm container not published yet.

## Steps to reproduce

  1. clear cookies manually
  2. load biotope.sh
  3. click accept in cookiebanner
  4. check if cookies are set or deleted
  5. go to privacy section and reopen cookie banner
  6. click decline in cookiebanner
  7. check if all cookies have been removed.

**Comment by rhafner** [comment]
I checked and got this behaviour:

1. clear cookies manually
2. load biotope.sh
3. click accept in cookiebanner
4. check if cookies are set => cookies are set
5. go to privacy section and reopen cookie banner
6. click decline in cookiebanner
7. check if all cookies have been removed. => does not work, cookies are not deleted

Please rework so that cookies are deleted when I decline them.
