### ISSUE TITLE
Text for cookie banner

### ISSUE THREAD

**Issue by IvailoStoyanov** [biotope/website#22]
do we already have to implement the most current CJEU/EUGH decision? so to explicitly:
- inform the user about the expiry date
- inform the user about (reason/puropse) of data collection and usage
- explicit active consent: unchecked checkbox
- explicitly disable cookies and tracking *without user consent*

**Comment by rhafner** [comment]
We came to the conclusion that we don't need a checkbox because we only have cookies from Google analytics. Therefore 2 buttons should be sufficient: accept or decline

Here is a draft for the text:
We use cookies so that we can offer you the best possible website experience. These are cookies which are used solely for anonymous statistical purposes to help us improve the user experience on the website. You are free to decide whether you would like to permit these cookies. Further information can be found in our Privacy Policy<link to privacy policy>.

**Comment by rhafner** [comment]
Google Analytics cookies expire after 2 years so the text is fine. https://developers.google.com/analytics/devguides/collection/analyticsjs/cookie-usage

**Comment by rhafner** [comment]
I got new information, that we should also added a tracking from LinkedIn. As soon as I know for sure, I will update the text accordingly

**Comment by rhafner** [comment]
Here the updated text:
We use cookies so that we can offer you the best possible website experience. These are cookies set by Google Analytics (expire in 24 months) and by the LinkedIn Insight Tag (expire in ? months) which are used solely for anonymous statistical purposes to help us improve the user experience on the website. You are free to decide whether you would like to permit these cookies. Further information can be found in our Privacy Policy.

@IvailoStoyanov Could please update the text? And determine the expiration date of the LinkedIn cookies?

**Comment by timomayer** [comment]
While i like your approach @jurekbarth the truth is also there are no google campaings we are doing or planning to do so at least for Google Analytics it is honest and true that we use it to learn how people use our page and improve it, for LinkedIn it is marketing related true.

**Comment by rhafner** [comment]
Thanks @jurekbarth for taking a closer look. I really appreciate you pointing this out to me. And I understand that you might feel upset for being deceived if you read this text on the final website.

I agree that the initial text which we wrote about how we use Google Analytics does not fit for the LinkedIn Insights Tag. That clearly is misleading. I will adjust the text so that it is clear that we use Google Analytics to learn about whether the website is useful for the user and where we can improve their experience and that we use the LinkedIn Insights Tag to measure whether our marketing campaign is effective.

Can you agree on this?

**Comment by rhafner** [comment]
Here a reworked text:
"We use cookies so that we can offer you the best possible website experience and see whether our marketing campaigns are effective. With Google Analytics (cookies expire in 24 months) we gain insights on how users interact with the website to better understand if their needs are met. With the LinkedIn Insight Tag (cookies expire in ? months) we gain insights whether our marketing efforts are having the desired effect. You are free to decline these cookies, but we'd be happy if you let use your anonymized data. Further information can be found in our Privacy Policy."

@jurekbarth / @timomayer : What do you think?

**Comment by jurekbarth** [comment]
@rhafner thanks for taking another look. I think it fits better now 👍
